from __future__ import annotations

import json
from pathlib import Path


NOTEBOOK_PATH = Path(__file__).resolve().parents[2] / "notebooks" / "mvp_pipeline.ipynb"


REPLACEMENTS: dict[int, list[str]] = {
    0: [
        "# MVP: семантическая карта региональной медиаповестки\n",
        "\n",
        "Этот notebook поддерживает два формальных режима работы:\n",
        "\n",
        "1. `Работа с готовыми локальными артефактами`\n",
        "2. `Полный локальный прогон`\n",
        "\n",
        "Канонический pipeline:\n",
        "\n",
        "1. очистка корпуса\n",
        "2. построение набора candidate-статей\n",
        "3. построение или переиспользование story embeddings\n",
        "4. оценка экономической релевантности, присвоение тем BoE и построение регионального индекса\n",
        "5. построение итоговых таблиц и графиков\n",
        "\n",
        "Публичная версия notebook очищена от outputs с прямыми текстовыми фрагментами корпуса и предназначена для безопасного воспроизведения pipeline и агрегированных результатов.\n",
    ],
    4: [
        "display(Markdown('## Режим выполнения'))\n",
        "mode_label = 'Работа с готовыми локальными артефактами' if USE_EXISTING_EMBEDDINGS else 'Полный локальный прогон'\n",
        "display(Markdown(f'**Выбранный режим:** `{mode_label}`'))\n",
        "display(Markdown(\n",
        "    f'`RUN_CLEANING={RUN_CLEANING}`, `RUN_CANDIDATES={RUN_CANDIDATES}`, '\n",
        "    f'`USE_EXISTING_EMBEDDINGS={USE_EXISTING_EMBEDDINGS}`, '\n",
        "    f'`MODEL_SIZE={MODEL_SIZE}`, `RUN_MODE={RUN_MODE}`'\n",
        "))\n",
        "display(Markdown(\n",
        "    f'Текущие артефакты: `cleaned={path_status(paths[\"cleaned_articles\"])}`, '\n",
        "    f'`candidate={path_status(paths[\"candidate_articles\"])}`, '\n",
        "    f'`lookup={path_status(paths[\"story_lookup\"])}`, '\n",
        "    f'`embeddings={path_status(paths[\"story_embeddings\"])}`'\n",
        "))\n",
    ],
    5: ["## 1. Очистка и проверка корпуса\n"],
    8: ["## 2. Построение candidate-набора\n"],
    10: [
        "candidate_head = read_parquet_head(\n",
        "    paths['candidate_articles'],\n",
        "    columns=['unique_article_id', 'date', 'week', 'region', 'candidate_source', 'strong_keyword_hit', 'weak_keyword_hit', 'url_section_hit'],\n",
        "    n_rows=5000,\n",
        ")\n",
        "candidate_source_distribution = candidate_head['candidate_source'].value_counts(dropna=False).rename_axis('candidate_source').to_frame('rows')\n",
        "\n",
        "candidate_summary = pd.Series({\n",
        "    'candidate_rows_in_preview': len(candidate_head),\n",
        "    'share_strong_keyword': float(candidate_head['strong_keyword_hit'].mean()),\n",
        "    'share_weak_keyword': float(candidate_head['weak_keyword_hit'].mean()),\n",
        "    'share_url_section': float(candidate_head['url_section_hit'].mean()),\n",
        "    'unique_regions_in_preview': int(candidate_head['region'].nunique()),\n",
        "    'unique_weeks_in_preview': int(pd.to_datetime(candidate_head['week']).nunique()),\n",
        "})\n",
        "\n",
        "display(Markdown('### Сводка candidate gate'))\n",
        "display(candidate_summary.to_frame('value'))\n",
        "display(Markdown('### Структура candidate_source в preview'))\n",
        "display(candidate_source_distribution)\n",
        "display(Markdown('### Preview candidate rows без текстовых фрагментов'))\n",
        "display(candidate_head.head(20))\n",
    ],
    11: ["## 3. Построение или переиспользование story embeddings\n"],
    12: [
        "if USE_EXISTING_EMBEDDINGS:\n",
        "    embedding_cmd = [\n",
        "        PYTHON,\n",
        "        'scripts/03_build_embeddings.py',\n",
        "        '--config',\n",
        "        str(CONFIG_PATH),\n",
        "        '--mode',\n",
        "        'bootstrap-existing',\n",
        "    ]\n",
        "    step3_label = 'Работа с готовыми локальными артефактами'\n",
        "else:\n",
        "    embedding_cmd = [\n",
        "        PYTHON,\n",
        "        'scripts/03_build_embeddings.py',\n",
        "        '--config',\n",
        "        str(CONFIG_PATH),\n",
        "        '--mode',\n",
        "        'build',\n",
        "        '--model-size',\n",
        "        MODEL_SIZE,\n",
        "        '--run-mode',\n",
        "        RUN_MODE,\n",
        "    ]\n",
        "    step3_label = 'Полный локальный прогон'\n",
        "\n",
        "embedding_run = subprocess.run(\n",
        "    embedding_cmd,\n",
        "    cwd=PROJECT_ROOT,\n",
        "    capture_output=True,\n",
        "    text=True,\n",
        "    check=True,\n",
        ")\n",
        "\n",
        "display(Markdown(f'### Сводка step 3 (`{step3_label}`)'))\n",
        "print(embedding_run.stdout)\n",
        "if embedding_run.stderr.strip():\n",
        "    print(embedding_run.stderr)\n",
    ],
    14: ["## 4. Economic gate, темы BoE и региональный индекс\n"],
    15: [
        "score_cmd = [\n",
        "    PYTHON,\n",
        "    'scripts/04_score_and_build_index.py',\n",
        "    '--config',\n",
        "    str(CONFIG_PATH),\n",
        "    '--model-size',\n",
        "    MODEL_SIZE,\n",
        "]\n",
        "if USE_EXISTING_EMBEDDINGS:\n",
        "    score_cmd.append('--reuse-embeddings')\n",
        "\n",
        "score_run = subprocess.run(\n",
        "    score_cmd,\n",
        "    cwd=PROJECT_ROOT,\n",
        "    capture_output=True,\n",
        "    text=True,\n",
        "    check=True,\n",
        ")\n",
        "\n",
        "display(Markdown(\n",
        "    f'### Сводка step 4 (`model_size={MODEL_SIZE}`, `reuse_embeddings={USE_EXISTING_EMBEDDINGS}`)'\n",
        "))\n",
        "print(score_run.stdout)\n",
        "if score_run.stderr.strip():\n",
        "    print(score_run.stderr)\n",
    ],
    16: [
        "scored_articles = pd.read_parquet(paths['scored_articles'])\n",
        "regional_index = pd.read_parquet(paths['regional_topic_index'])\n",
        "\n",
        "scored_articles['week'] = pd.to_datetime(scored_articles['week'])\n",
        "regional_index['week'] = pd.to_datetime(regional_index['week'])\n",
        "\n",
        "econ_mask = scored_articles['is_econ']\n",
        "scoring_summary = pd.Series({\n",
        "    'scored_articles': len(scored_articles),\n",
        "    'economic_articles': int(econ_mask.sum()),\n",
        "    'boe_topic_articles': int(scored_articles['assigned_topic'].isin(BOE_TOPICS).sum()),\n",
        "    'other_econ_articles': int(scored_articles['assigned_topic'].eq('other_econ').sum()),\n",
        "    'regions_in_index': int(regional_index['region'].nunique()),\n",
        "    'weeks_in_index': int(regional_index['week'].nunique()),\n",
        "    'other_econ_share_among_econ_articles': float(scored_articles.loc[econ_mask, 'assigned_topic'].eq('other_econ').mean()),\n",
        "})\n",
        "topic_distribution = scored_articles.loc[econ_mask, 'assigned_topic'].value_counts().rename_axis('assigned_topic').to_frame('rows')\n",
        "\n",
        "display(Markdown('### Сводка semantic scoring'))\n",
        "display(scoring_summary.to_frame('value'))\n",
        "display(Markdown('### Распределение assigned_topic среди экономических статей'))\n",
        "display(topic_distribution.head(12))\n",
    ],
    18: ["## 5. Итоговые таблицы и графики\n"],
    20: [
        "hot_pairs = pd.read_csv(paths['hot_regions_topics'])\n",
        "\n",
        "reference_week = 'no active BoE week found'\n",
        "if not hot_pairs.empty:\n",
        "    reference_week = pd.to_datetime(hot_pairs['week']).max().date().isoformat()\n",
        "\n",
        "display(Markdown(f'### Reference week used for latest outputs: `{reference_week}`'))\n",
        "display(hot_pairs.head(20))\n",
        "display(Markdown('Публичная версия notebook не выводит representative snippets и review tables с прямыми текстовыми фрагментами корпуса.'))\n",
    ],
    21: [
        "with CONFIG_PATH.open('r', encoding='utf-8') as handle:\n",
        "    latest_settings = yaml.safe_load(handle)\n",
        "\n",
        "latest_paths = {key: PROJECT_ROOT / value for key, value in latest_settings['paths'].items()}\n",
        "\n",
        "figure_specs = [\n",
        "    ('### Карта: reference week', 'latest_heatmap'),\n",
        "    ('### Карта: среднее за декабрь 2022', 'monthly_heatmap'),\n",
        "    ('### Карта: общий top-risk по регионам', 'overall_risk_map'),\n",
        "    ('### Карта: доминирующая тема по регионам', 'dominant_topic_map'),\n",
        "    ('### График трендов: showcase topic', 'hot_topic_trends'),\n",
        "    ('### График трендов: совокупный региональный риск', 'overall_region_trends'),\n",
        "]\n",
        "\n",
        "for title, key in figure_specs:\n",
        "    path = latest_paths.get(key)\n",
        "    display(Markdown(title))\n",
        "    if path is None:\n",
        "        display(Markdown(f'Path `{key}` is missing from `settings.yaml`.'))\n",
        "        continue\n",
        "    if not path.exists():\n",
        "        display(Markdown(f'File not found: `{path}`'))\n",
        "        continue\n",
        "    display(Image(filename=str(path)))\n",
    ],
}


def main() -> None:
    with NOTEBOOK_PATH.open("r", encoding="utf-8") as handle:
        notebook = json.load(handle)

    for idx, source in REPLACEMENTS.items():
        notebook["cells"][idx]["source"] = source

    with NOTEBOOK_PATH.open("w", encoding="utf-8") as handle:
        json.dump(notebook, handle, ensure_ascii=False, indent=1)


if __name__ == "__main__":
    main()

